# Generated by Django 5.2.14 on 2026-05-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='instamojo_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='instamojo_payment_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='payment_method',
            field=models.CharField(default='INSTAMOJO', max_length=50),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='utr_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
