# Generated by Django 5.2.14 on 2026-05-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_contribution_instamojo_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='cashfree_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='cashfree_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='payment_method',
            field=models.CharField(default='CASHFREE', max_length=50),
        ),
    ]
