# Generated by Django 6.0.5 on 2026-05-07 16:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('RELIGIOUS', 'Religious'), ('INFRASTRUCTURE', 'Infrastructure'), ('SOCIAL', 'Social'), ('CULTURAL', 'Cultural'), ('EDUCATION', 'Education'), ('HEALTH', 'Health')], max_length=50)),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('raised_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VOTING', 'Voting'), ('ACTIVE', 'Active'), ('FUNDED', 'Funded'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='campaigns/covers/')),
                ('campaign_upi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign_qr_image', models.ImageField(blank=True, null=True, upload_to='campaigns/qrs/')),
                ('requires_voting', models.BooleanField(default=False)),
                ('voting_threshold', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignBudgetItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('is_unlocked', models.BooleanField(default=False)),
                ('proof_photo', models.ImageField(blank=True, null=True, upload_to='campaigns/milestones/')),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='campaigns/updates/')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote', models.BooleanField()),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sponsor_name', models.CharField(max_length=255)),
                ('sponsor_logo', models.ImageField(blank=True, null=True, upload_to='sponsors/')),
                ('sponsor_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_cash', models.BooleanField(default=True)),
                ('in_kind_description', models.TextField(blank=True, null=True)),
                ('in_kind_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
