# Generated by Django 6.0.5 on 2026-05-07 16:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('icon_url', models.CharField(max_length=500)),
                ('criteria_type', models.CharField(choices=[('FIRST_DONOR', 'First Donor'), ('TOP_3', 'Top 3'), ('CAMPAIGN_COUNT', 'Campaign Count'), ('AMOUNT_THRESHOLD', 'Amount Threshold'), ('STREAK', 'Streak')], max_length=50)),
                ('criteria_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badges.badge')),
            ],
        ),
    ]
