# Generated by Django 6.0.5 on 2026-05-07 16:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('CONTRIBUTION_APPROVED', 'Contribution Approved'), ('NEW_CAMPAIGN', 'New Campaign'), ('EXPENSE_POSTED', 'Expense Posted'), ('PLEDGE_DUE', 'Pledge Due'), ('BADGE_EARNED', 'Badge Earned'), ('FLAG_RAISED', 'Flag Raised')], max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
            ],
        ),
    ]
