# Generated by Django 6.0.5 on 2026-05-07 16:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('BEFORE', 'Before'), ('DURING', 'During'), ('AFTER', 'After'), ('EVENT', 'Event'), ('GENERAL', 'General')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('video_url', models.CharField(blank=True, max_length=500, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='campaigns.campaign')),
            ],
        ),
    ]
